### PR TITLE
Only animate opacity for the dialog blocker layer

### PR DESCRIPTION
**Pull request by CalebQ42**
Done by making the layer a part of the main UI instead of on each dialog seperately.

### CODE REVIEW

**Comment by CalebQ42** [comment]
Fixed the awkwardness of seeing the edges of the dialog blocker when dialogs are shown, as well as the scroll bars briefly showing up when the spring effect makes the blocker larger then the screen.

**Comment by CalebQ42** [comment]
Never used React before so it might be a bit on the messy side.

**Comment by CalebQ42** [comment]
I've removed the build files, but it seems you manually allowed them earlier. In general it's a bad idea to check compiled files into git as they're contents are already provided via the source code. Additionally it over complicates commits as it doesn't conform the the traditional format that git likes. If you do want to provide the compiled version, a better way would be to create a Github Action that automatically compiles a version and puts it as a release.

**Comment by austintirrell** [comment]
@CalebQ42 I'm hosting this on Amplify in AWS, and it doesn't automatically build. I don't have that setting enabled if it does. So I was providing it a build folder. I can start a Bitwarden account for us if you want to take a look 🤷‍♂️

**Comment by CalebQ42** [comment]
Ah, I see. I've never dealt with anything AWS. I wouldn't mind looking at it at some point, but for right now I'll just revert that real quick

**Comment by CalebQ42** [comment]
Actually, this PR is really messy, let me put up a new, clean one

**Pull request closed without merging**
